// M4 tests for the ESCHAM CPU dequant kernels (ggml-escham.c).
//
// (a) Unit: C tile decode (escham_decode_tile_k2/k3) vs the oracle
//     escham_cpu.reconstruct_code, on real tiles cut out of the checkpoint
//     (fixtures generated by gen_fixture_m4.py). Expect BITWISE equality;
//     rms relatif reported as well.
// (b) Graph: full pre/post path around a ggml mul_mat --
//         xs = x * rin ; xp = T128(xs) ; z = Wh^T @ xp ;
//         y = T128(z) * rout + bias          (T128 = escham_t128_f32)
//     against the reference y computed in torch by gen_fixture_m4.py.
//     Criterion: relative rms < 1e-3.
//
// Usage: test-escha-m4 [fixture]

#include "ggml.h"
#include "ggml-backend.h"
#include "ggml-cpu.h"
#include "ggml-escham.h"

#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define FIXTURE_DEFAULT "/home/yaniss/hermes-work/escha/port/fixture_m4.bin"
#define FIXTURE_MAGIC 0x45534D34u // 'ESM4'
// (a) is bitwise: any mismatched fp16 cell fails, rms is informational only
#define CRIT_GRAPH 1e-3f

static void *read_all(const char *path, size_t *n) {
    FILE *f = fopen(path, "rb");
    if (!f) { fprintf(stderr, "cannot open %s\n", path); return NULL; }
    fseek(f, 0, SEEK_END);
    long sz = ftell(f);
    fseek(f, 0, SEEK_SET);
    void *buf = malloc((size_t)sz);
    if (!buf) { fclose(f); return NULL; }
    if (fread(buf, 1, (size_t)sz, f) != (size_t)sz) { fclose(f); free(buf); return NULL; }
    fclose(f);
    *n = (size_t)sz;
    return buf;
}

static float rel_rms(const float *a, const float *b, size_t n) {
    double se = 0.0, sb = 0.0;
    for (size_t i = 0; i < n; i++) {
        double d = (double)a[i] - (double)b[i];
        se += d * d;
        sb += (double)b[i] * (double)b[i];
    }
    return (float)(sqrt(se / n) / (sqrt(sb / n) + 1e-12));
}

static const uint8_t *cur;
static const uint8_t *take(size_t n) {
    const uint8_t *p = cur;
    cur += n;
    return p;
}
static uint32_t rd_u32(void) {
    uint32_t v;
    memcpy(&v, take(4), 4);
    return v;
}

static int test_record(const char *name, int K, int IC, int OC, int NT, int NR,
                       const uint16_t *codes_unit, const uint16_t *exp_unit,
                       const uint16_t *packed,
                       const float *x, const float *rin, const float *rout,
                       const float *bias, const float *ref_y) {
    int fails = 0;

    // ---- decode the whole tensor with our kernels (exercised by the graph) --
    uint16_t *whc = malloc((size_t)IC * OC * sizeof(uint16_t));
    if (!whc) { fprintf(stderr, "%s: OOM\n", name); return 1; }
    {
        const int64_t itc = IC / 16, otc = OC / 16;
        uint16_t tile[256];
        for (int64_t it = 0; it < itc; it++) {
            for (int64_t ot = 0; ot < otc; ot++) {
                const uint16_t *src = packed + (it * otc + ot) * 16 * K;
                if (K == 2) {
                    escham_decode_tile_k2(src, tile);
                } else {
                    escham_decode_tile_k3(src, tile);
                }
                for (int r = 0; r < 16; r++) {
                    memcpy(whc + (it * 16 + r) * OC + ot * 16, tile + r * 16,
                           16 * sizeof(uint16_t));
                }
            }
        }
    }

    // ---------- (a) unit tiles ----------
    size_t mismatches = 0;
    double worst_rms = 0.0;
    for (int t = 0; t < NT; t++) {
        uint16_t out[256];
        memset(out, 0xEE, sizeof(out)); // sentinel: proves full coverage
        if (K == 2) {
            escham_decode_tile_k2(codes_unit + t * 32, out);
        } else {
            escham_decode_tile_k3(codes_unit + t * 48, out);
        }
        for (int i = 0; i < 256; i++) {
            if (out[i] == 0xEEEEu) {
                fprintf(stderr, "%s: tile %d cell %d NEVER WRITTEN\n", name, t, i);
                fails++;
                break;
            }
            if (out[i] != exp_unit[t * 256 + i]) {
                mismatches++;
                if (mismatches <= 4) {
                    fprintf(stderr, "%s: tile %d cell %d got %04x want %04x\n",
                            name, t, i, out[i], exp_unit[t * 256 + i]);
                }
            }
        }
        float fo[256], fe[256];
        for (int i = 0; i < 256; i++) {
            fo[i] = ggml_fp16_to_fp32(out[i]);
            fe[i] = ggml_fp16_to_fp32(exp_unit[t * 256 + i]);
        }
        double r = rel_rms(fo, fe, 256);
        if (r > worst_rms) worst_rms = r;
    }
    printf("%s: unit  K=%d  %3d tiles  mismatched cells %zu/%d  worst rms %.3e  %s\n",
           name, K, NT, mismatches, NT * 256, worst_rms,
           (mismatches == 0) ? "OK" : "FAIL");
    if (mismatches > 0) fails++;

    // ---------- (b) graph ----------
    const int64_t nr = NR, ic = IC, oc = OC;
    // dense T128 matrices dominate: ic^2 + oc^2 fp32, plus Wh fp16, x, and slack
    size_t pool = (size_t)(ic * ic * 4 + oc * oc * 4 + ic * oc * 2 +
                           (ic + oc) * nr * 4 * 8 + 256ull * 1024 * 1024);
    struct ggml_init_params ip = {
        .mem_size = pool,
        .mem_buffer = NULL,
        .no_alloc = false,
    };
    struct ggml_context *ctx = ggml_init(ip);

    // x stored column-wise: ne=(IC, NR), data[j*IC + i] = sample j, feature i.
    // Fixture stream is feature-major (i*NR + j), so transpose while loading.
    struct ggml_tensor *tx = ggml_new_tensor_2d(ctx, GGML_TYPE_F32, ic, nr);
    {
        float *dst = (float *)tx->data;
        for (int64_t i = 0; i < ic; i++) {
            for (int64_t j = 0; j < nr; j++) {
                dst[j * ic + i] = x[i * nr + j];
            }
        }
    }

    struct ggml_tensor *trin = ggml_new_tensor_2d(ctx, GGML_TYPE_F32, ic, 1);
    memcpy(trin->data, rin, ggml_nbytes(trin));

    struct ggml_tensor *trout = ggml_new_tensor_2d(ctx, GGML_TYPE_F32, oc, 1);
    memcpy(trout->data, rout, ggml_nbytes(trout));

    struct ggml_tensor *tbias = ggml_new_tensor_2d(ctx, GGML_TYPE_F32, oc, 1);
    memcpy(tbias->data, bias, ggml_nbytes(tbias));

    // W_hat decoded by our own kernels above, fp16, ne=(IC, OC). mul_mat reads
    // an F16 weight as (OC, IC) row-major (row o = data[o*ic + i]), so fill it
    // transposed: data[o*ic + i] = Wh[i][o]; mul_mat then computes
    // z[o,j] = sum_i Wh[i][o]*xs[i,j]
    struct ggml_tensor *tw = ggml_new_tensor_2d(ctx, GGML_TYPE_F16, ic, oc);
    for (int64_t i = 0; i < ic; i++) {
        for (int64_t o = 0; o < oc; o++) {
            ((uint16_t *)tw->data)[o * ic + i] = whc[i * oc + o];
        }
    }

    // T128 matrices (symmetric, orthogonal), one per side: IC x IC and OC x OC.
    // Built with the kernel under test: each row holds one 1.0 and is run
    // through escham_vec_had128_f32, so the graph exercises the same code
    // path as the runtime vector transforms.
    struct ggml_tensor *tTin = ggml_new_tensor_2d(ctx, GGML_TYPE_F32, ic, ic);
    struct ggml_tensor *tTout = ggml_new_tensor_2d(ctx, GGML_TYPE_F32, oc, oc);
    memset(tTin->data, 0, ggml_nbytes(tTin));
    memset(tTout->data, 0, ggml_nbytes(tTout));
    for (int64_t i = 0; i < ic; i++) {
        ((float *)tTin->data)[i * ic + i] = 1.0f;
        escham_vec_had128_f32((float *)tTin->data + i * ic, ic);
    }
    for (int64_t i = 0; i < oc; i++) {
        ((float *)tTout->data)[i * oc + i] = 1.0f;
        escham_vec_had128_f32((float *)tTout->data + i * oc, oc);
    }

    // xs = x * rin, then the input-side Hadamard: xp = T128(x * rin)
    struct ggml_tensor *xs = ggml_mul(ctx, tx, trin);
    struct ggml_tensor *xp = ggml_mul_mat(ctx, tTin, xs);
    // fork quirk: op_params[1] (mul_mat hint) is left uninitialized by
    // ggml_mul_mat(); stale pool bytes == 1 silently reroute to the FWHT path.
    ggml_mul_mat_set_hint(xp, GGML_HINT_NONE);
    // z = Wh^T @ xp -> ne=(OC, NR)
    struct ggml_tensor *z = ggml_mul_mat(ctx, tw, xp);
    ggml_mul_mat_set_hint(z, GGML_HINT_NONE);
    // h = T128(z) : mul_mat(tT (OC,OC), z (OC,NR)) -> ne=(OC,NR),
    // h[o,j] = sum_l tT[l,o] * z[l,j]  (T symmetric).
    // Order matters: rout is diagonal, T128 is dense per 128-block, they do
    // NOT commute. Reference chain is T128(z) FIRST, then * rout.
    struct ggml_tensor *h = ggml_mul_mat(ctx, tTout, z);
    ggml_mul_mat_set_hint(h, GGML_HINT_NONE);
    // y = h * rout (rout broadcast along rows of h), still ne=(OC, NR)
    struct ggml_tensor *y = ggml_mul(ctx, h, trout);
    // res = y + bias
    struct ggml_tensor *res = ggml_add(ctx, y, tbias);

    struct ggml_cgraph *gf = ggml_new_graph(ctx);
    ggml_build_forward_expand(gf, res);
    ggml_backend_t cpu = ggml_backend_cpu_init();
    if (!cpu) { fprintf(stderr, "%s: no cpu backend\n", name); ggml_free(ctx); return 1; }
    const char *nth_env = getenv("ESCHAM_M4_NTH");
    ggml_backend_cpu_set_n_threads(cpu, nth_env ? atoi(nth_env) : 4);
    enum ggml_status gst = ggml_backend_graph_compute(cpu, gf);
    if (gst != GGML_STATUS_SUCCESS) {
        fprintf(stderr, "%s: graph compute failed (%d)\n", name, (int)gst);
        fails++;
    }
    ggml_backend_free(cpu);

    if (getenv("ESCHAM_M4_DUMP")) {
        FILE *fd = fopen(getenv("ESCHAM_M4_DUMP"), "wb");
        if (fd) {
            fwrite(res->data, sizeof(float), (size_t)oc * nr, fd);
            fclose(fd);
        }
    }

    // res is (OC, NR) in ggml order (data[j*oc + o]); the fixture stream is
    // row-major over (OC, NR): ref[o*nr + j]. Reorder before comparing.
    float rms = -1.0f;
    float *res_rm = malloc((size_t)oc * nr * sizeof(float));
    if (res_rm) {
        const float *rd = (const float *)res->data;
        for (int64_t o = 0; o < oc; o++) {
            for (int64_t j = 0; j < nr; j++) {
                res_rm[o * nr + j] = rd[j * oc + o];
            }
        }
        rms = rel_rms(res_rm, ref_y, (size_t)oc * nr);
        free(res_rm);
    } else {
        fprintf(stderr, "%s: OOM\n", name);
        fails++;
    }
    printf("%s: graph K=%d  IC=%d OC=%d NR=%d  rms rel %.3e  %s\n",
           name, K, IC, OC, NR, rms, (rms < CRIT_GRAPH) ? "OK" : "FAIL");
    if (getenv("ESCHAM_M4_DEBUG")) {
        const float *d_xs = (const float *)xs->data;
        const float *d_xp = (const float *)xp->data;
        const float *d_z  = (const float *)z->data;
        printf("  tx[0..7]    : %.6f %.6f %.6f %.6f %.6f %.6f %.6f %.6f\n",
               ((const float *)tx->data)[0], ((const float *)tx->data)[1],
               ((const float *)tx->data)[2], ((const float *)tx->data)[3],
               ((const float *)tx->data)[4], ((const float *)tx->data)[5],
               ((const float *)tx->data)[6], ((const float *)tx->data)[7]);
        printf("  rin[0..3]   : %.6f %.6f %.6f %.6f\n",
               ((const float *)trin->data)[0], ((const float *)trin->data)[1],
               ((const float *)trin->data)[2], ((const float *)trin->data)[3]);
        printf("  xs[i,0] i0-3: %.6f %.6f %.6f %.6f\n",
               d_xs[0], d_xs[nr], d_xs[2 * nr], d_xs[3 * nr]);
        printf("  xs[0,j] j0-3: %.6f %.6f %.6f %.6f\n",
               d_xs[0], d_xs[1], d_xs[2], d_xs[3]);
        printf("  xp[i,0] i0-3: %.6f %.6f %.6f %.6f\n",
               d_xp[0], d_xp[nr], d_xp[2 * nr], d_xp[3 * nr]);
        {
            const float *tI = (const float *)tTin->data;
            printf("  tTin r0[0..3] : %.6f %.6f %.6f %.6f\n", tI[0], tI[1], tI[2], tI[3]);
            printf("  tTin r1[0..3] : %.6f %.6f %.6f %.6f\n", tI[ic], tI[ic + 1], tI[ic + 2], tI[ic + 3]);
            printf("  tTin r0[124..127]: %.6f %.6f %.6f %.6f\n", tI[124], tI[125], tI[126], tI[127]);
            printf("  tTin r0[128..131]: %.6f %.6f %.6f %.6f\n", tI[128], tI[129], tI[130], tI[131]);
            printf("  tTin r128[128..131]: %.6f %.6f %.6f %.6f\n",
                   tI[128 * ic + 128], tI[128 * ic + 129], tI[128 * ic + 130], tI[128 * ic + 131]);
        }
        printf("  xp[0,0..7]: %.6f %.6f %.6f %.6f %.6f %.6f %.6f %.6f\n",
               d_xp[0], d_xp[1], d_xp[2], d_xp[3], d_xp[4], d_xp[5], d_xp[6], d_xp[7]);
        printf("  z[o,0] o0-3 : %.6f %.6f %.6f %.6f\n",
               d_z[0], d_z[nr], d_z[2 * nr], d_z[3 * nr]);
        printf("  WhC[0,0..1]=(%.6f,%.6f) WhC[1,0]=%.6f WhC[100,37]=%.6f\n",
               ggml_fp16_to_fp32(whc[0 * oc + 0]), ggml_fp16_to_fp32(whc[0 * oc + 1]),
               ggml_fp16_to_fp32(whc[1 * oc + 0]), ggml_fp16_to_fp32(whc[100 * oc + 37]));
        // full-chain manual recomputation, no ggml ops:
        // z = Wh^T @ xp ; h = T128(z) ; y = h*rout ; y += bias ; vs ref_y
        float *sman = malloc((size_t)oc * sizeof(float));
        if (sman) {
            // first: graph z vs manual z on the same (tw, xp) buffers
            const float *xj0 = (const float *)xp->data;
            printf("  z graph vs manual (o=0..3, j=0):");
            for (int64_t o = 0; o < 4 && o < oc; o++) {
                double acc = 0.0;
                for (int64_t i = 0; i < ic; i++) {
                    acc += (double)ggml_fp16_to_fp32(whc[i * oc + o]) * (double)xj0[i];
                }
                printf(" %.6f/%.6f", d_z[o * nr], (float)acc);
            }
            printf("\n");
            // integrity: tw must still hold whc after the graph run
            size_t diff = 0;
            const uint16_t *twv = (const uint16_t *)tw->data;
            for (size_t i = 0; i < (size_t)ic * oc; i++) {
                if (twv[i] != whc[i]) diff++;
            }
            printf("  tw cells differing from whc after compute: %zu\n", diff);
            // primitive checks: from_float conversion and vec_dot_f16 accuracy
            {
                extern void ggml_cpu_fp32_to_fp16(const float * x, ggml_fp16_t * y, int64_t n);
                extern void ggml_vec_dot_f16(int n, float * s, size_t bs,
                                             ggml_fp16_t * x, size_t bx,
                                             ggml_fp16_t * y, size_t by, int nrc);
                enum { NN = 256 };
                ggml_fp16_t hf[NN];
                float xf[NN];
                for (int i = 0; i < NN; i++) xf[i] = 0.01f * (float)(i - NN / 2);
                ggml_cpu_fp32_to_fp16(xf, hf, NN);
                size_t pd = 0;
                for (int i = 0; i < NN; i++) {
                    if (hf[i] != ggml_fp32_to_fp16(xf[i])) pd++;
                }
                printf("  fp32->fp16 primitive mismatches: %zu/%d\n", pd, NN);
                float dot = 0.0f;
                ggml_vec_dot_f16(NN, &dot, sizeof(float), hf, sizeof(ggml_fp16_t),
                                 hf, sizeof(ggml_fp16_t), 1);
                double ref = 0.0;
                for (int i = 0; i < NN; i++) ref += (double)xf[i] * (double)xf[i];
                printf("  vec_dot_f16(h,h)=%.4f ref=%.4f\n", dot, ref);
            }
            double se = 0.0, sb = 0.0;
            for (int64_t j = 0; j < nr; j++) {
                const float *xj = (const float *)xp->data + j * ic;
                for (int64_t o = 0; o < oc; o++) {
                    double acc = 0.0;
                    for (int64_t i = 0; i < ic; i++) {
                        acc += (double)ggml_fp16_to_fp32(whc[i * oc + o]) * (double)xj[i];
                    }
                    sman[o] = (float)acc;
                }
                escham_vec_had128_f32(sman, oc);
                for (int64_t o = 0; o < oc; o++) {
                    const double dv = (double)sman[o] * (double)rout[o] + (double)bias[o]
                                    - (double)ref_y[o * nr + j];
                    se += dv * dv;
                    sb += (double)ref_y[o * nr + j] * (double)ref_y[o * nr + j];
                }
            }
            free(sman);
            printf("  manual-chain rms rel vs ref: %.3e\n",
                   sqrt(se / (double)((size_t)oc * nr)) / (sqrt(sb / (double)((size_t)oc * nr)) + 1e-12));
        }
    }
    if (!(rms < CRIT_GRAPH)) fails++;

    free(whc);
    ggml_free(ctx);
    return fails;
}

int main(int argc, char **argv) {
    const char *path = (argc > 1) ? argv[1] : FIXTURE_DEFAULT;
    size_t n;
    void *buf = read_all(path, &n);
    if (!buf) return 1;
    cur = (const uint8_t *)buf;

    int total_fails = 0;
    if (rd_u32() != FIXTURE_MAGIC) { fprintf(stderr, "bad magic\n"); return 1; }
    (void)rd_u32(); // version
    int nrec = (int)rd_u32();
    printf("fixture %s: %d records\n", path, nrec);
    for (int r = 0; r < nrec; r++) {
        uint32_t nl = rd_u32();
        char name[128];
        memcpy(name, take(nl), nl);
        name[nl] = 0;
        int K = (int)rd_u32(), IC = (int)rd_u32(), OC = (int)rd_u32();
        int NT = (int)rd_u32(), NR = (int)rd_u32();
        const uint16_t *codes_unit = (const uint16_t *)take((size_t)NT * 16 * K * 2);
        const uint16_t *exp_unit = (const uint16_t *)take((size_t)NT * 256 * 2);
        const uint16_t *packed = (const uint16_t *)take((size_t)(IC / 16) * (OC / 16) * 16 * K * 2);
        const float *x = (const float *)take((size_t)IC * NR * 4);
        const float *rin = (const float *)take((size_t)IC * 4);
        const float *rout = (const float *)take((size_t)OC * 4);
        const float *bias = (const float *)take((size_t)OC * 4);
        const float *ref = (const float *)take((size_t)OC * NR * 4);
        printf("-- %s: K=%d IC=%d OC=%d NT=%d NR=%d\n", name, K, IC, OC, NT, NR);
        total_fails += test_record(name, K, IC, OC, NT, NR, codes_unit, exp_unit,
                                   packed, x, rin, rout, bias, ref);
    }
    free(buf);
    printf("\nverdict: %s (%d failing checks)\n", total_fails ? "FAIL" : "PASS", total_fails);
    return total_fails ? 1 : 0;
}
